// <auto-generated>
// This code was generated by a Windows Forms designer.
// </auto-generated>

namespace ChibiKartToolkit
{
    partial class Form1
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            MenuStrip1 = new MenuStrip();
            FileToolStripMenuItem = new ToolStripMenuItem();
            AboutToolStripMenuItem = new ToolStripMenuItem();
            ExportToolStripMenuItem = new ToolStripMenuItem();
            PAKToolStripMenuItem = new ToolStripMenuItem();
            ImportToolStripMenuItem = new ToolStripMenuItem();
            MiscToolStripMenuItem = new ToolStripMenuItem();
            XORTestToolStripMenuItem = new ToolStripMenuItem();
            DecryptStringToolStripMenuItem = new ToolStripMenuItem();
            packetToolStripMenuItem = new ToolStripMenuItem();
            ToolStripMenuItemInspectXML = new ToolStripMenuItem();
            btnStartServer = new Button();
            lbxMessages = new ListBox();
            ofdInputPAK = new OpenFileDialog();
            btnStartWebServer = new Button();
            BtnLaunchChibiKart = new Button();
            label1 = new Label();
            linkLabel1 = new LinkLabel();
            btnServerSettings = new Button();
            btnSaveMessages = new Button();
            MenuStrip1.SuspendLayout();
            SuspendLayout();
            // 
            // MenuStrip1
            // 
            MenuStrip1.Items.AddRange(new ToolStripItem[] { FileToolStripMenuItem, ExportToolStripMenuItem, ImportToolStripMenuItem, MiscToolStripMenuItem, packetToolStripMenuItem });
            MenuStrip1.Location = new Point(0, 0);
            MenuStrip1.Name = "MenuStrip1";
            MenuStrip1.Size = new Size(1090, 24);
            MenuStrip1.TabIndex = 0;
            MenuStrip1.Text = "menuStrip1";
            // 
            // FileToolStripMenuItem
            // 
            FileToolStripMenuItem.DropDownItems.AddRange(new ToolStripItem[] { AboutToolStripMenuItem });
            FileToolStripMenuItem.Name = "FileToolStripMenuItem";
            FileToolStripMenuItem.Size = new Size(37, 20);
            FileToolStripMenuItem.Text = "File";
            // 
            // AboutToolStripMenuItem
            // 
            AboutToolStripMenuItem.Name = "AboutToolStripMenuItem";
            AboutToolStripMenuItem.Size = new Size(107, 22);
            AboutToolStripMenuItem.Text = "About";
            AboutToolStripMenuItem.Click += AboutToolStripMenuItem_Click;
            // 
            // ExportToolStripMenuItem
            // 
            ExportToolStripMenuItem.DropDownItems.AddRange(new ToolStripItem[] { PAKToolStripMenuItem });
            ExportToolStripMenuItem.Name = "ExportToolStripMenuItem";
            ExportToolStripMenuItem.Size = new Size(53, 20);
            ExportToolStripMenuItem.Text = "Export";
            // 
            // PAKToolStripMenuItem
            // 
            PAKToolStripMenuItem.Name = "PAKToolStripMenuItem";
            PAKToolStripMenuItem.Size = new Size(95, 22);
            PAKToolStripMenuItem.Text = "PAK";
            PAKToolStripMenuItem.Click += PAKToolStripMenuItem_Click;
            // 
            // ImportToolStripMenuItem
            // 
            ImportToolStripMenuItem.Name = "ImportToolStripMenuItem";
            ImportToolStripMenuItem.Size = new Size(55, 20);
            ImportToolStripMenuItem.Text = "Import";
            // 
            // MiscToolStripMenuItem
            // 
            MiscToolStripMenuItem.DropDownItems.AddRange(new ToolStripItem[] { XORTestToolStripMenuItem, DecryptStringToolStripMenuItem });
            MiscToolStripMenuItem.Name = "MiscToolStripMenuItem";
            MiscToolStripMenuItem.Size = new Size(44, 20);
            MiscToolStripMenuItem.Text = "Misc";
            // 
            // XORTestToolStripMenuItem
            // 
            XORTestToolStripMenuItem.Name = "XORTestToolStripMenuItem";
            XORTestToolStripMenuItem.Size = new Size(146, 22);
            XORTestToolStripMenuItem.Text = "XOR Test";
            XORTestToolStripMenuItem.Click += XORTestToolStripMenuItem_Click;
            // 
            // DecryptStringToolStripMenuItem
            // 
            DecryptStringToolStripMenuItem.Name = "DecryptStringToolStripMenuItem";
            DecryptStringToolStripMenuItem.Size = new Size(146, 22);
            DecryptStringToolStripMenuItem.Text = "DecryptString";
            DecryptStringToolStripMenuItem.Click += DecryptStringToolStripMenuItem_Click;
            // 
            // packetToolStripMenuItem
            // 
            packetToolStripMenuItem.DropDownItems.AddRange(new ToolStripItem[] { ToolStripMenuItemInspectXML });
            packetToolStripMenuItem.Name = "packetToolStripMenuItem";
            packetToolStripMenuItem.Size = new Size(54, 20);
            packetToolStripMenuItem.Text = "Packet";
            // 
            // ToolStripMenuItemInspectXML
            // 
            ToolStripMenuItemInspectXML.Name = "ToolStripMenuItemInspectXML";
            ToolStripMenuItemInspectXML.Size = new Size(112, 22);
            ToolStripMenuItemInspectXML.Text = "Inspect";
            ToolStripMenuItemInspectXML.Click += ToolStripMenuItemInspectXML_Click;
            // 
            // btnStartServer
            // 
            btnStartServer.Location = new Point(12, 27);
            btnStartServer.Name = "btnStartServer";
            btnStartServer.Size = new Size(152, 34);
            btnStartServer.TabIndex = 1;
            btnStartServer.Text = "Start Game Server";
            btnStartServer.UseVisualStyleBackColor = true;
            btnStartServer.Click += btnStartServer_Click;
            // 
            // lbxMessages
            // 
            lbxMessages.FormattingEnabled = true;
            lbxMessages.ItemHeight = 15;
            lbxMessages.Location = new Point(12, 95);
            lbxMessages.Name = "lbxMessages";
            lbxMessages.Size = new Size(1027, 409);
            lbxMessages.TabIndex = 2;
            // 
            // ofdInputPAK
            // 
            ofdInputPAK.FileName = "OpenFileDialog1";
            // 
            // btnStartWebServer
            // 
            btnStartWebServer.Location = new Point(204, 27);
            btnStartWebServer.Name = "btnStartWebServer";
            btnStartWebServer.Size = new Size(157, 34);
            btnStartWebServer.TabIndex = 3;
            btnStartWebServer.Text = "Start Web Server";
            btnStartWebServer.UseVisualStyleBackColor = true;
            btnStartWebServer.Click += btnStartWebServer_Click;
            // 
            // BtnLaunchChibiKart
            // 
            BtnLaunchChibiKart.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            BtnLaunchChibiKart.Location = new Point(521, 24);
            BtnLaunchChibiKart.Name = "BtnLaunchChibiKart";
            BtnLaunchChibiKart.Size = new Size(149, 37);
            BtnLaunchChibiKart.TabIndex = 4;
            BtnLaunchChibiKart.Text = "Launch Chibi Kart";
            BtnLaunchChibiKart.UseVisualStyleBackColor = true;
            BtnLaunchChibiKart.Click += BtnLaunchChibiKart_Click;
            // 
            // label1
            // 
            label1.AutoSize = true;
            label1.Font = new Font("Segoe UI", 8F, FontStyle.Italic);
            label1.Location = new Point(678, 37);
            label1.Name = "label1";
            label1.Size = new Size(85, 13);
            label1.TabIndex = 5;
            label1.Text = "hardcoded value";
            // 
            // linkLabel1
            // 
            linkLabel1.AutoSize = true;
            linkLabel1.Location = new Point(16, 68);
            linkLabel1.Name = "linkLabel1";
            linkLabel1.Size = new Size(142, 15);
            linkLabel1.TabIndex = 6;
            linkLabel1.TabStop = true;
            linkLabel1.Text = "Show/Edit Responses.xml";
            linkLabel1.LinkClicked += linkLabel1_ShowResponsesXML;
            // 
            // btnServerSettings
            // 
            btnServerSettings.Location = new Point(383, 49);
            btnServerSettings.Name = "btnServerSettings";
            btnServerSettings.Size = new Size(112, 25);
            btnServerSettings.TabIndex = 7;
            btnServerSettings.Text = "Server Settings";
            btnServerSettings.UseVisualStyleBackColor = true;
            btnServerSettings.Click += btnServerSettings_Click;
            // 
            // btnSaveMessages
            // 
            btnSaveMessages.Location = new Point(311, 516);
            btnSaveMessages.Name = "btnSaveMessages";
            btnSaveMessages.Size = new Size(376, 26);
            btnSaveMessages.TabIndex = 8;
            btnSaveMessages.Text = "Sauvegarder les messages";
            btnSaveMessages.UseVisualStyleBackColor = true;
            btnSaveMessages.Click += btnSaveMessages_Click;
            // 
            // Form1
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(1090, 575);
            Controls.Add(btnSaveMessages);
            Controls.Add(btnServerSettings);
            Controls.Add(linkLabel1);
            Controls.Add(label1);
            Controls.Add(BtnLaunchChibiKart);
            Controls.Add(btnStartWebServer);
            Controls.Add(lbxMessages);
            Controls.Add(btnStartServer);
            Controls.Add(MenuStrip1);
            MainMenuStrip = MenuStrip1;
            Name = "Form1";
            Text = "Chibi Kart Tool";
            FormClosing += Form1_FormClosing;
            MenuStrip1.ResumeLayout(false);
            MenuStrip1.PerformLayout();
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion

        private System.Windows.Forms.MenuStrip MenuStrip1;
        private System.Windows.Forms.ToolStripMenuItem FileToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem AboutToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem ExportToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem PAKToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem ImportToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem MiscToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem XORTestToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem DecryptStringToolStripMenuItem;
        private System.Windows.Forms.Button btnStartServer;
        private System.Windows.Forms.ListBox lbxMessages;
        private System.Windows.Forms.OpenFileDialog ofdInputPAK;
        private System.Windows.Forms.Button btnStartWebServer;
        private ToolStripMenuItem packetToolStripMenuItem;
        private Button BtnLaunchChibiKart;
        private ToolStripMenuItem ToolStripMenuItemInspectXML;
        private Label label1;
        private LinkLabel linkLabel1;
        private Button btnServerSettings;
        private Button btnSaveMessages;
    }
}
