// <auto-generated>
// This code was generated by a Windows Forms designer.
// </auto-generated>

namespace ChibiKartToolkit
{
    partial class Form1
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            this.MenuStrip1 = new System.Windows.Forms.MenuStrip();
            this.FileToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.AboutToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.ExportToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.PAKToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.ImportToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.MiscToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.XORTestToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.DecryptStringToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.btnStartServer = new System.Windows.Forms.Button();
            this.lbxMessages = new System.Windows.Forms.ListBox();
            this.ofdInputPAK = new System.Windows.Forms.OpenFileDialog();
            this.btnStartWebServer = new System.Windows.Forms.Button();
            this.MenuStrip1.SuspendLayout();
            this.SuspendLayout();

            // MenuStrip1
            this.MenuStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.FileToolStripMenuItem,
            this.ExportToolStripMenuItem,
            this.ImportToolStripMenuItem,
            this.MiscToolStripMenuItem});
            this.MenuStrip1.Location = new System.Drawing.Point(0, 0);
            this.MenuStrip1.Name = "MenuStrip1";
            this.MenuStrip1.Size = new System.Drawing.Size(800, 24);
            this.MenuStrip1.TabIndex = 0;
            this.MenuStrip1.Text = "menuStrip1";

            // FileToolStripMenuItem
            this.FileToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.AboutToolStripMenuItem});
            this.FileToolStripMenuItem.Name = "FileToolStripMenuItem";
            this.FileToolStripMenuItem.Size = new System.Drawing.Size(37, 20);
            this.FileToolStripMenuItem.Text = "File";

            // AboutToolStripMenuItem
            this.AboutToolStripMenuItem.Name = "AboutToolStripMenuItem";
            this.AboutToolStripMenuItem.Size = new System.Drawing.Size(107, 22);
            this.AboutToolStripMenuItem.Text = "About";
            this.AboutToolStripMenuItem.Click += new System.EventHandler(this.AboutToolStripMenuItem_Click);

            // ExportToolStripMenuItem
            this.ExportToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.PAKToolStripMenuItem});
            this.ExportToolStripMenuItem.Name = "ExportToolStripMenuItem";
            this.ExportToolStripMenuItem.Size = new System.Drawing.Size(53, 20);
            this.ExportToolStripMenuItem.Text = "Export";

            // PAKToolStripMenuItem
            this.PAKToolStripMenuItem.Name = "PAKToolStripMenuItem";
            this.PAKToolStripMenuItem.Size = new System.Drawing.Size(95, 22);
            this.PAKToolStripMenuItem.Text = "PAK";
            this.PAKToolStripMenuItem.Click += new System.EventHandler(this.PAKToolStripMenuItem_Click);

            // ImportToolStripMenuItem
            this.ImportToolStripMenuItem.Name = "ImportToolStripMenuItem";
            this.ImportToolStripMenuItem.Size = new System.Drawing.Size(55, 20);
            this.ImportToolStripMenuItem.Text = "Import";

            // MiscToolStripMenuItem
            this.MiscToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.XORTestToolStripMenuItem,
            this.DecryptStringToolStripMenuItem});
            this.MiscToolStripMenuItem.Name = "MiscToolStripMenuItem";
            this.MiscToolStripMenuItem.Size = new System.Drawing.Size(44, 20);
            this.MiscToolStripMenuItem.Text = "Misc";

            // XORTestToolStripMenuItem
            this.XORTestToolStripMenuItem.Name = "XORTestToolStripMenuItem";
            this.XORTestToolStripMenuItem.Size = new System.Drawing.Size(146, 22);
            this.XORTestToolStripMenuItem.Text = "XOR Test";
            this.XORTestToolStripMenuItem.Click += new System.EventHandler(this.XORTestToolStripMenuItem_Click);

            // DecryptStringToolStripMenuItem
            this.DecryptStringToolStripMenuItem.Name = "DecryptStringToolStripMenuItem";
            this.DecryptStringToolStripMenuItem.Size = new System.Drawing.Size(146, 22);
            this.DecryptStringToolStripMenuItem.Text = "DecryptString";
            this.DecryptStringToolStripMenuItem.Click += new System.EventHandler(this.DecryptStringToolStripMenuItem_Click);

            // btnStartServer
            this.btnStartServer.Location = new System.Drawing.Point(12, 27);
            this.btnStartServer.Name = "btnStartServer";
            this.btnStartServer.Size = new System.Drawing.Size(126, 34);
            this.btnStartServer.TabIndex = 1;
            this.btnStartServer.Text = "Start Game Server";
            this.btnStartServer.UseVisualStyleBackColor = true;
            this.btnStartServer.Click += new System.EventHandler(this.btnStartServer_Click);

            // lbxMessages
            this.lbxMessages.FormattingEnabled = true;
            this.lbxMessages.ItemHeight = 15;
            this.lbxMessages.Location = new System.Drawing.Point(12, 77);
            this.lbxMessages.Name = "lbxMessages";
            this.lbxMessages.Size = new System.Drawing.Size(776, 364);
            this.lbxMessages.TabIndex = 2;

            // ofdInputPAK
            this.ofdInputPAK.FileName = "OpenFileDialog1";

            // btnStartWebServer
            this.btnStartWebServer.Location = new System.Drawing.Point(204, 27);
            this.btnStartWebServer.Name = "btnStartWebServer";
            this.btnStartWebServer.Size = new System.Drawing.Size(157, 34);
            this.btnStartWebServer.TabIndex = 3;
            this.btnStartWebServer.Text = "Start Web Server";
            this.btnStartWebServer.UseVisualStyleBackColor = true;
            this.btnStartWebServer.Click += new System.EventHandler(this.btnStartWebServer_Click);

            // Form1
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(800, 455);
            this.Controls.Add(this.btnStartWebServer);
            this.Controls.Add(this.lbxMessages);
            this.Controls.Add(this.btnStartServer);
            this.Controls.Add(this.MenuStrip1);
            this.MainMenuStrip = this.MenuStrip1;
            this.Name = "Form1";
            this.Text = "Form1";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.Form1_FormClosing);
            this.MenuStrip1.ResumeLayout(false);
            this.MenuStrip1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        #endregion

        private System.Windows.Forms.MenuStrip MenuStrip1;
        private System.Windows.Forms.ToolStripMenuItem FileToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem AboutToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem ExportToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem PAKToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem ImportToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem MiscToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem XORTestToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem DecryptStringToolStripMenuItem;
        private System.Windows.Forms.Button btnStartServer;
        private System.Windows.Forms.ListBox lbxMessages;
        private System.Windows.Forms.OpenFileDialog ofdInputPAK;
        private System.Windows.Forms.Button btnStartWebServer;
    }
}
